### ISSUE TITLE
Upgrades not given for spells learned through certain talents

### ISSUE THREAD

**Issue by ApexWoW** [ApexWoW/Argus#3]
Example, the Pyroblast spell is learned through a Mage talent. Upon choosing a talent like Pyroblast, the new player is stuck with Rank 1 of said spell and needs to make a few gold and head for a trainer in order to learn the upgrades. We'll need to find a way for people to train spells taught by talents up to level 58 after creating a character.

**Comment by Argonn** [comment]
Giving out a higher rank 'up-front' gives all the ranks automatically to the character. I need to look into a 'correct' way of tackling this.

**Comment by Argonn** [comment]
The fix seems to be working as intented after some testing on the test realm. 
All ranks (below or equal to 58 are learned).

- Learning spells up until 58 on picking rank 1 talent.
- Learning spells from the trainer higher than your lvl 58 version
- Unlearning talents gained from the rank 1 talent.
- Unlearning talents gained from the rank 1 talent and newer ranks from the trainers.

All scenario's are flawless.

**Comment by ApexWoW** [comment]
Tested and appears to be working fine.
