### ISSUE TITLE
Grant people max skill for weapons and armors upon first joining

### ISSUE THREAD

**Issue by ApexWoW** [ApexWoW/Argus#5]
Currently new characters will have to grind their weapon and armor skill all the way up to a level coherent with their character level. What we need to implement is a way for new characters to start with weapon and armor skill completely maxed out for a level 58 character.

**Comment by Argonn** [comment]
When a new character has been created, this character will automatically have the maxed out weapon/defense skills (290 for level 58). This change is already in effect!
