### ISSUE TITLE
Shamans have the priest version of Cure Disease

### ISSUE THREAD

**Issue by freshbull** [ApexWoW/Argus#6]
Shamans have the priest version of Cure Disease in the general tab of the spellbook.

![screenshot_23](https://user-images.githubusercontent.com/34074165/35184054-bb15eb84-fdf0-11e7-8f00-46c9a7b9657d.jpg)

**Comment by ApexWoW** [comment]
Thanks for your report. This issue should be fixed after the next server reset.
